# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

## Build stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package*.json tsconfig.json ./
COPY src ./src
RUN npm ci
RUN npm run build

## Production stage
FROM node:lts-alpine AS runner
WORKDIR /app

# Copy built files and install only production deps
COPY --from=builder /app/build ./build
COPY package*.json ./
RUN npm ci --production

# Default entrypoint for MCP server over stdio
ENTRYPOINT ["node", "build/index.js"]
